
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8100

zuul:
  routes:
    Author-Service:
      url: http://localhost:9095
   Bibliothek-Service:
      url: http://localhost:8072
    UserEntity-Service:
      url: http://localhost:8082
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


